sudo: required
services:
  - docker

before_install:
  - docker build -t captainphilipp/frontend -f Dockerfile.dev .

script:
  - docker run captainphilipp/frontend npm run test -- --coverage

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region:   "eu-west-2"
  app:      "docker-react"
  env:      "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-140913918749"
  bucket_path: docker
  access_key_id: $AWS_BEANSTALK_ACCESS_KEY
  secret_access_key:
    secure: $AWS_BEANSTALK_SECRET_KEY
